### ISSUE TITLE
Django haystack with Whoosh error when using rebuild_index or update_index

### ISSUE THREAD

**Issue by sam-thecoder** [dokipen/whoosh#1]
I get an error when I try to run rebuild_index or update index, I've asked the question on stackoverflow here http://stackoverflow.com/questions/33804525/django-haystack-whoosh-error-attributeerror-unknownfielderror-object-has-no

**Comment by dokipen** [comment]
This isn't the main repository, just a fork I made to do some work. I don't know where the official one lives.
